Implement is_planar()
graphviz-perl/Graph pull request #31
Opened 2024-06-26 08:02 UTC by merkys

This PR implements graph planarity check in `is_planar()` for undirected graphs. The implementation is based on [left-right planarity test](https://en.wikipedia.org/w/index.php?title=Left-right_planarity_test&oldid=1158148963), whose accessable full-text (at least to me) origin seems to be [de Fraysseix and Rosenstiehl (1985)](https://doi.org/10.1007%2FBF02579375).

I have not included the mention of left-right planarity test in the code as I was unsure where it belongs. Should it be visible in the POD, or only in the code, as implementation detail?

2024-06-26 12:57 UTC, mohawk2 requested changes
Just some nits - thank you for your continuing contributions! Please could you also keep `commit --amend`ing, instead of creating several commits for one conceptual change? I believe you'd agree with me that the change isn't actually done till it's got tests and doc.

2024-06-26 13:00 UTC, merkys commented on lib/Graph.pm
> +
Is it OK if I do changes to `is_bipartite()` on another branch? Or is it OK to do them in this one?

2024-06-26 13:03 UTC, merkys commented
Thank you for such a prompt review! I will definitely try to stick to your style guidelines regarding git and whitespace usage.

2024-06-26 17:22 UTC, mohawk2 commented on lib/Graph.pm
> +
If it's a separate commit from the `is_planar` one, making two in total, then on this would be fine!

2024-06-27 15:15 UTC, merkys commented on lib/Graph.pod
> +Return true if the graph is planar. Currently only works with undirected graphs.
Added an implementation note with a reference in c649ecf6f164cd955246ac5cea887e58384295be.

2024-06-27 15:17 UTC, merkys commented
I think you can squash the commits on GitHub before the merge. I probably cannot do that on my side, as this will need force-pushing (AFAIK allowed only for repository owners).

2024-06-28 09:40 UTC, mohawk2 commented
In fact, you absolutely can force-push to your own non-main branch at any time, and it is highly normal to do so. I'm happy to squash/merge this time, but please bear that in mind and force-push another time :-)

I'll release this today.

2024-06-28 09:41 UTC, merged

2024-06-28 10:02 UTC, merkys commented
Oh right, I indeed can force-push to my own branch. Next time I will try to use less commits :) Thanks a lot for reviewing and merging this!

2024-06-29 15:08 UTC, mohawk2 commented
Thank you for making this module more capable! It's not a lot of effort to make new releases, but each does potentially make work for downstreams (including yourself!). This is just to request that if you *know* you have several new things you want to add, to say so on the earlier ones, in case that can reduce the number of releases in a given week ;-)

2024-07-01 06:22 UTC, merkys commented
Yes, sorry about that. I will let you know my plans beforehand next time.

2024-07-02 17:25 UTC, mohawk2 commented
It's a nice problem for the maintainer to have! Just a thought :-)